version: '3.6'
services:
    superset:
        image: pietrocannalire/superset:base
        container_name: superset
        depends_on: 
            - redis
        environment:
            - CACHE_ENABLED=redis
            - LOAD_EXAMPLES=True
        ports:
            - 8088:8088
        volumes:
#            - ./config:/etc/superset
            - ./sqlite:/var/lib/superset            

    redis:
        image: redis
        container_name: redis
        restart: always
        volumes:
            - ./redis:/data

    postgres:
        image: postgres:9.6
        container_name: postgres
        environment:
            - POSTGRES_PASSWORD=superset
            - POSTGRES_USER=superset
            - POSTGRES_DB=superset
        ports:
            - 5432:5432
        volumes:
            - ./postgresql:/var/lib/postgresql/data
        command: postgres
