version: '3.6'
services:
    superset:
        image: pietrocannalire/superset:0.29.0rc7
        container_name: superset
        environment:
            - SUPERSETFIRSTNAME=${SUPERSETFIRSTNAME}
            - SUPERSETLASTNAME=${SUPERSETLASTNAME}
            - CACHE_ENABLED=True
        ports:
            - 8088:8088
        volumes:
            - ./config:/etc/superset
            - ./sqlite:/var/lib/superset

    postgres-superset:
        image: postgres:9.6
        container_name: postgres-superset
        environment:
            - POSTGRES_PASSWORD=superset
            - POSTGRES_USER=superset
            - POSTGRES_DB=superset
        ports:
            - 5432:5432
        volumes:
            - ./postgresql:/var/lib/postgresql/data
        command: postgres
