version: '3.6'
services:
    superset:
        image: pietrocannalire/superset:base
        container_name: superset
        environment:
            - SUPERSETFIRSTNAME=$SUPERSETFIRSTNAME
            - SUPERSETLASTNAME=$SUPERSETLASTNAME
            - LOGOUT_REDIRECTURL=$LOGOUT_REDIRECTURL
            - SHIB_HEADERS=$SHIB_HEADERS
            - SQLALCHEMY_DATA_URI=$SQLALCHEMY_DATA_URI
        ports:
            - 8088:8088
        volumes:
            - ./config:/etc/superset

    postgres-superset:
        image: postgres:9.6
        container_name: postgres-superset
        environment:
            - POSTGRES_PASSWORD=superset
            - POSTGRES_USER=superset
            - POSTGRES_DB=superset
        ports:
            - 5432:5432
        volumes:
            - ./postgresql:/var/lib/postgresql/data
        command: postgres
