#!/bin/bash

set -e

# Init superset.db if not present
if [ ! -f /var/lib/superset/superset.db ] ; then
	touch /var/lib/superset/superset.db
	chmod 755 /var/lib/superset/superset.db
fi

# Create an admin user
fabmanager create-admin --app superset --username $SUPERSETUSER --firstname $SUPERSETUSER --lastname $SUPERSETUSER --email $SUPERSETUSER@superset.csi.it --password superset

# Initialize the database
superset db upgrade

# Create default roles and permissions
superset init